logger:
  enable: true
  pretty_backtrace: true
  level: info
  format: json

server:
  port: {{ get_env(name="PORT", default="8080") }}
  binding: 0.0.0.0
  host: http://localhost
  middlewares:
    fallback:
      enable: false
    static:
      enable: false
    limit_payload:
      enable: true
      body_limit: 27mb

workers:
  mode: BackgroundQueue

queue:
  kind: Postgres
  uri: {{ get_env(name="LOCO_QUEUE_URL", default="postgres://featherlane:featherlane@localhost:5432/featherlane") }}
  dangerously_flush: false
  enable_logging: false
  min_connections: 1
  max_connections: 4
  poll_interval_sec: 1
  num_workers: 2
  reaper:
    age_minutes: 15
    interval_seconds: 60

database:
  uri: {{ get_env(name="DATABASE_URL", default="postgres://featherlane:featherlane@localhost:5432/featherlane") }}
  enable_logging: false
  connect_timeout: 500
  idle_timeout: 500
  min_connections: 1
  max_connections: 10
  auto_migrate: true
  dangerously_truncate: false
  dangerously_recreate: false
