use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[allow(clippy::too_many_lines)]
#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(PolicyImports::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(PolicyImports::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(PolicyImports::OrganizationId)
                            .uuid()
                            .not_null(),
                    )
                    .col(ColumnDef::new(PolicyImports::Status).string().not_null())
                    .col(ColumnDef::new(PolicyImports::InputKind).string().not_null())
                    .col(
                        ColumnDef::new(PolicyImports::SourceType)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(PolicyImports::Title).text().not_null())
                    .col(
                        ColumnDef::new(PolicyImports::Jurisdiction)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(PolicyImports::EffectiveFrom).timestamp_with_time_zone())
                    .col(ColumnDef::new(PolicyImports::SourceUrl).text())
                    .col(ColumnDef::new(PolicyImports::OriginalFilename).text())
                    .col(ColumnDef::new(PolicyImports::DeclaredMimeType).string())
                    .col(
                        ColumnDef::new(PolicyImports::DetectedMimeType)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PolicyImports::ByteLength)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PolicyImports::ContentSha256)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PolicyImports::RawObjectKey)
                            .text()
                            .not_null(),
                    )
                    .col(ColumnDef::new(PolicyImports::NormalizedObjectKey).text())
                    .col(ColumnDef::new(PolicyImports::ParserKind).string())
                    .col(ColumnDef::new(PolicyImports::ParserVersion).string())
                    .col(ColumnDef::new(PolicyImports::ModelProvider).string())
                    .col(ColumnDef::new(PolicyImports::ModelName).string())
                    .col(ColumnDef::new(PolicyImports::PromptVersion).string())
                    .col(ColumnDef::new(PolicyImports::PageCount).integer())
                    .col(
                        ColumnDef::new(PolicyImports::CoveragePayload)
                            .json_binary()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PolicyImports::CandidateCount)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(PolicyImports::VerificationStatus)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(PolicyImports::VerifiedBy).text())
                    .col(ColumnDef::new(PolicyImports::VerifiedAt).timestamp_with_time_zone())
                    .col(ColumnDef::new(PolicyImports::VerificationNotes).text())
                    .col(ColumnDef::new(PolicyImports::FailureCode).string())
                    .col(ColumnDef::new(PolicyImports::FailureDetail).text())
                    .col(ColumnDef::new(PolicyImports::IdempotencyKey).string())
                    .col(ColumnDef::new(PolicyImports::CompiledSourceId).uuid())
                    .col(ColumnDef::new(PolicyImports::CompiledPolicyPackId).uuid())
                    .col(
                        ColumnDef::new(PolicyImports::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PolicyImports::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(ColumnDef::new(PolicyImports::CompletedAt).timestamp_with_time_zone())
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_policy_imports_organization")
                            .from(PolicyImports::Table, PolicyImports::OrganizationId)
                            .to(Organizations::Table, Organizations::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_policy_imports_source")
                            .from(PolicyImports::Table, PolicyImports::CompiledSourceId)
                            .to(Sources::Table, Sources::Id)
                            .on_delete(ForeignKeyAction::SetNull),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_policy_imports_pack")
                            .from(PolicyImports::Table, PolicyImports::CompiledPolicyPackId)
                            .to(PolicyPacks::Table, PolicyPacks::Id)
                            .on_delete(ForeignKeyAction::SetNull),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_policy_imports_tenant_created")
                    .table(PolicyImports::Table)
                    .col(PolicyImports::OrganizationId)
                    .col(PolicyImports::CreatedAt)
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_policy_imports_content_hash")
                    .table(PolicyImports::Table)
                    .col(PolicyImports::OrganizationId)
                    .col(PolicyImports::ContentSha256)
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_policy_imports_status")
                    .table(PolicyImports::Table)
                    .col(PolicyImports::OrganizationId)
                    .col(PolicyImports::Status)
                    .col(PolicyImports::UpdatedAt)
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("uq_policy_imports_idempotency")
                    .table(PolicyImports::Table)
                    .col(PolicyImports::OrganizationId)
                    .col(PolicyImports::IdempotencyKey)
                    .unique()
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(PolicyCandidates::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(PolicyCandidates::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(PolicyCandidates::OrganizationId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PolicyCandidates::PolicyImportId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PolicyCandidates::Position)
                            .integer()
                            .not_null(),
                    )
                    .col(ColumnDef::new(PolicyCandidates::Origin).string().not_null())
                    .col(
                        ColumnDef::new(PolicyCandidates::Fingerprint)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(PolicyCandidates::Key).string().not_null())
                    .col(
                        ColumnDef::new(PolicyCandidates::Statement)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PolicyCandidates::LocatorPayload)
                            .json_binary()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PolicyCandidates::SourceExcerpt)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PolicyCandidates::Applicability)
                            .json_binary()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PolicyCandidates::Exceptions)
                            .json_binary()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PolicyCandidates::RequiredEvidence)
                            .json_binary()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PolicyCandidates::SuggestedSeverity)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(PolicyCandidates::SuggestedRule).json_binary())
                    .col(
                        ColumnDef::new(PolicyCandidates::MappingStatus)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(PolicyCandidates::ModelConfidence).double())
                    .col(ColumnDef::new(PolicyCandidates::ModelPayloadSha256).string())
                    .col(ColumnDef::new(PolicyCandidates::Status).string().not_null())
                    .col(ColumnDef::new(PolicyCandidates::ReviewPayload).json_binary())
                    .col(
                        ColumnDef::new(PolicyCandidates::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PolicyCandidates::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_policy_candidates_organization")
                            .from(PolicyCandidates::Table, PolicyCandidates::OrganizationId)
                            .to(Organizations::Table, Organizations::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_policy_candidates_import")
                            .from(PolicyCandidates::Table, PolicyCandidates::PolicyImportId)
                            .to(PolicyImports::Table, PolicyImports::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("uq_policy_candidate_fingerprint")
                    .table(PolicyCandidates::Table)
                    .col(PolicyCandidates::PolicyImportId)
                    .col(PolicyCandidates::Fingerprint)
                    .unique()
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("uq_policy_candidate_key")
                    .table(PolicyCandidates::Table)
                    .col(PolicyCandidates::PolicyImportId)
                    .col(PolicyCandidates::Key)
                    .unique()
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_policy_candidates_review_queue")
                    .table(PolicyCandidates::Table)
                    .col(PolicyCandidates::OrganizationId)
                    .col(PolicyCandidates::PolicyImportId)
                    .col(PolicyCandidates::Status)
                    .col(PolicyCandidates::Position)
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(PolicyCandidateReviews::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(PolicyCandidateReviews::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(PolicyCandidateReviews::OrganizationId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PolicyCandidateReviews::CandidateId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PolicyCandidateReviews::Decision)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PolicyCandidateReviews::ReviewerId)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PolicyCandidateReviews::Notes)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PolicyCandidateReviews::BeforePayload)
                            .json_binary()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PolicyCandidateReviews::AfterPayload)
                            .json_binary()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PolicyCandidateReviews::ReviewedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_policy_candidate_reviews_organization")
                            .from(
                                PolicyCandidateReviews::Table,
                                PolicyCandidateReviews::OrganizationId,
                            )
                            .to(Organizations::Table, Organizations::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_policy_candidate_reviews_candidate")
                            .from(
                                PolicyCandidateReviews::Table,
                                PolicyCandidateReviews::CandidateId,
                            )
                            .to(PolicyCandidates::Table, PolicyCandidates::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_policy_candidate_reviews_history")
                    .table(PolicyCandidateReviews::Table)
                    .col(PolicyCandidateReviews::OrganizationId)
                    .col(PolicyCandidateReviews::CandidateId)
                    .col(PolicyCandidateReviews::ReviewedAt)
                    .to_owned(),
            )
            .await?;
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .table(PolicyCandidateReviews::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(PolicyCandidates::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(PolicyImports::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await
    }
}

#[derive(DeriveIden)]
enum Organizations {
    Table,
    Id,
}

#[derive(DeriveIden)]
enum Sources {
    Table,
    Id,
}

#[derive(DeriveIden)]
enum PolicyPacks {
    Table,
    Id,
}

#[derive(DeriveIden)]
enum PolicyImports {
    Table,
    Id,
    OrganizationId,
    Status,
    InputKind,
    SourceType,
    Title,
    Jurisdiction,
    EffectiveFrom,
    SourceUrl,
    OriginalFilename,
    DeclaredMimeType,
    DetectedMimeType,
    ByteLength,
    ContentSha256,
    RawObjectKey,
    NormalizedObjectKey,
    ParserKind,
    ParserVersion,
    ModelProvider,
    ModelName,
    PromptVersion,
    PageCount,
    CoveragePayload,
    CandidateCount,
    VerificationStatus,
    VerifiedBy,
    VerifiedAt,
    VerificationNotes,
    FailureCode,
    FailureDetail,
    IdempotencyKey,
    CompiledSourceId,
    CompiledPolicyPackId,
    CreatedAt,
    UpdatedAt,
    CompletedAt,
}

#[derive(DeriveIden)]
enum PolicyCandidates {
    Table,
    Id,
    OrganizationId,
    PolicyImportId,
    Position,
    Origin,
    Fingerprint,
    Key,
    Statement,
    LocatorPayload,
    SourceExcerpt,
    Applicability,
    Exceptions,
    RequiredEvidence,
    SuggestedSeverity,
    SuggestedRule,
    MappingStatus,
    ModelConfidence,
    ModelPayloadSha256,
    Status,
    ReviewPayload,
    CreatedAt,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum PolicyCandidateReviews {
    Table,
    Id,
    OrganizationId,
    CandidateId,
    Decision,
    ReviewerId,
    Notes,
    BeforePayload,
    AfterPayload,
    ReviewedAt,
}
