[package]
name = "governance-persistence"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
governance-application.workspace = true
governance-domain.workspace = true
governance-targets.workspace = true
governance-telemetry.workspace = true
sea-orm.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
uuid.workspace = true

[lints]
workspace = true

[dev-dependencies]
governance-migration = { path = "../../migration" }
sea-orm-migration.workspace = true
tokio.workspace = true
